### ISSUE TITLE
EarQuiz not playing audio

### ISSUE THREAD

**Issue by mindfulnessbergamo** [Gdalik/EarQuiz_Frequencies#2]
I am using EarQuiz 0.1.4 on a Windows 10 computer. I installed it via binary file. I do not understand why I cannot play the attached wav file in Preview mode: it's 44.1KHz, 16 bit, mono. I have played other wav files previously in EarQuiz with no issue. What's wrong with this one? Thanks. p.s. I had to zip the file because Github does not support attaching wav files
[base.zip](https://github.com/Gdalik/EarQuiz_Frequencies/files/14416490/base.zip)

**Comment by Gdalik** [comment]
@mindfulnessbergamo You cannot load it because [its duration is less than 10 seconds long](https://earquiz.org/manuals/earquiz-frequencies-help/create-edit-save-playlists/). This is not supported because the minimal possible slice/example length is 10 seconds. You should see the duration colored with red in the Playlist and the message about this in the status bar when trying to load it.
